#############################################################################
# Makefile for building: GPS
# Generated by qmake (2.01a) (Qt 4.5.0) on: Mon Dec 26 23:09:48 2011
# Project:  GPS.pro
# Template: app
# Command: /opt/EmbedSky/qt-4.5/__install/arm/bin/qmake -spec /opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qws/linux-arm-g++ -unix -o Makefile GPS.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qws/linux-arm-g++ -I. -I/opt/EmbedSky/qt-4.5/__install/arm/include/QtCore -I/opt/EmbedSky/qt-4.5/__install/arm/include/QtNetwork -I/opt/EmbedSky/qt-4.5/__install/arm/include/QtGui -I/opt/EmbedSky/qt-4.5/__install/arm/include -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/EmbedSky/qt-4.5/__install/arm/lib
LIBS          = $(SUBLIBS)  -L/opt/EmbedSky/qt-4.5/__install/arm//lib -lQtGui -L/tslib-1.4/lib -L/opt/EmbedSky/qt-4.5/__install/arm//lib -lts -lQtNetwork -lQtCore -lm -lrt -ldl -lpthread
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /opt/EmbedSky/qt-4.5/__install/arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		gps.cpp \
		mainwindow.cpp \
		recordposition.cpp \
		httpconnection.cpp moc_gps.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		gps.o \
		mainwindow.o \
		recordposition.o \
		httpconnection.o \
		moc_gps.o \
		moc_mainwindow.o
DIST          = /opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/g++.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/unix.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/linux.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/qws.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qconfig.pri \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt_functions.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt_config.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/exclusive_builds.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/default_pre.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/release.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/default_post.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/warn_on.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/unix/thread.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/moc.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/resources.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/uic.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/yacc.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/lex.prf \
		GPS.pro
QMAKE_TARGET  = GPS
DESTDIR       = 
TARGET        = GPS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPS.pro  /opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qws/linux-arm-g++/qmake.conf /opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/g++.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/unix.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/linux.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/qws.conf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qconfig.pri \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt_functions.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt_config.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/exclusive_builds.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/default_pre.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/release.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/default_post.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/warn_on.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/unix/thread.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/moc.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/resources.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/uic.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/yacc.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/lex.prf \
		/opt/EmbedSky/qt-4.5/__install/arm/lib/libQtGui.prl \
		/opt/EmbedSky/qt-4.5/__install/arm/lib/libQtNetwork.prl \
		/opt/EmbedSky/qt-4.5/__install/arm/lib/libQtCore.prl
	$(QMAKE) -spec /opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qws/linux-arm-g++ -unix -o Makefile GPS.pro
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/g++.conf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/unix.conf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/linux.conf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/common/qws.conf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qconfig.pri:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt_functions.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt_config.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/exclusive_builds.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/default_pre.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/release.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/default_post.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/warn_on.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/qt.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/unix/thread.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/moc.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/resources.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/uic.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/yacc.prf:
/opt/EmbedSky/qt-4.5/__install/arm/mkspecs/features/lex.prf:
/opt/EmbedSky/qt-4.5/__install/arm/lib/libQtGui.prl:
/opt/EmbedSky/qt-4.5/__install/arm/lib/libQtNetwork.prl:
/opt/EmbedSky/qt-4.5/__install/arm/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/EmbedSky/qt-4.5/__install/arm/mkspecs/qws/linux-arm-g++ -unix -o Makefile GPS.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GPS1.0.0 || $(MKDIR) .tmp/GPS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GPS1.0.0/ && $(COPY_FILE) --parents gps.h mainwindow.h recordposition.h httpconnection.h .tmp/GPS1.0.0/ && $(COPY_FILE) --parents main.cpp gps.cpp mainwindow.cpp recordposition.cpp httpconnection.cpp .tmp/GPS1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/GPS1.0.0/ && (cd `dirname .tmp/GPS1.0.0` && $(TAR) GPS1.0.0.tar GPS1.0.0 && $(COMPRESS) GPS1.0.0.tar) && $(MOVE) `dirname .tmp/GPS1.0.0`/GPS1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GPS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_gps.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gps.cpp moc_mainwindow.cpp
moc_gps.cpp: mainwindow.h \
		gps.h \
		recordposition.h \
		httpconnection.h \
		gps.h
	/opt/EmbedSky/qt-4.5/__install/arm//bin/moc $(DEFINES) $(INCPATH) gps.h -o moc_gps.cpp

moc_mainwindow.cpp: gps.h \
		mainwindow.h \
		recordposition.h \
		httpconnection.h \
		mainwindow.h
	/opt/EmbedSky/qt-4.5/__install/arm//bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/EmbedSky/qt-4.5/__install/arm/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		gps.h \
		recordposition.h \
		httpconnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

gps.o: gps.cpp gps.h \
		mainwindow.h \
		recordposition.h \
		httpconnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gps.o gps.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		gps.h \
		recordposition.h \
		httpconnection.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

recordposition.o: recordposition.cpp recordposition.h \
		mainwindow.h \
		gps.h \
		httpconnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recordposition.o recordposition.cpp

httpconnection.o: httpconnection.cpp httpconnection.h \
		mainwindow.h \
		gps.h \
		recordposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpconnection.o httpconnection.cpp

moc_gps.o: moc_gps.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gps.o moc_gps.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

